#' Prepare Synthetic Benthic Data Table
#'
#' Converts synthetic point- or cover-based benthic sampling observations into a
#' standardised data table suitable for downstream processing and ReefCloud-style
#' export. The function harmonises identifiers (site, transect, survey), formats
#' benthic attributes, and then applies reef-selection and cover calculations via
#' `select_process_reefs()`.
#'
#' @title Prepare Synthetic Data Table
#'
#' @param data_fixed_locs_points An `sf` object containing synthetic fine-scale
#' point or quadrat data generated by
#' `sampling_design_fine_scale_points()` or equivalent. Must include:
#' \itemize{
#'   \item `Reef`, `Site`, `Transect`, `Year`, `Date`
#'   \item `Depth`, `Latitude`, `Longitude`
#'   \item For points: `POINT_NO`, `Group`
#'   \item For quadrats/cover: `Value`, `Quad`, `Group`
#'   \item Geometry column
#' }
#'
#' @param data_type A string specifying the structure of the input dataset:
#' \itemize{
#'   \item `"points"` – raw point-level classifications (HCC, SC, MA, etc.)
#'   \item `"cover"` – aggregated quadrat or percentage cover measurements
#' }
#'
#' @return A processed `data.frame` containing:
#' \itemize{
#'   \item Project, site, transect and survey metadata
#'   \item Coordinates and depth
#'   \item Either:
#'     \itemize{
#'       \item Point identifiers and benthic class (for `data_type = "points"`)
#'       \item Quadrat numbers and numeric cover (for `data_type = "cover"`)
#'     }
#'   \item Reef and site identifiers extracted and standardised
#'   \item Final benthic metrics (`COUNT`, `COVER`, `COVER_TRUE`) after reef
#'         selection and processing by `select_process_reefs()`
#' }
#'
#' @details
#' The function:
#' \itemize{
#'   \item Creates consistent project, site, survey, and transect identifiers
#'   \item Adds point-level or quadrat-level variables depending on `data_type`
#'   \item Selects only the variables required for synthetic export
#'   \item Calls `select_process_reefs()` to:
#'     \itemize{
#'       \item Select a subset of reefs according to `config_lrge`
#'       \item Compute TRUE and selected cover values
#'       \item Extract and standardise reef and site codes
#'       \item Attach year and benthic cover metrics
#'     }
#' }
#'
#' @seealso [select_process_reefs()]
#'
#' @author Murray/Julie
#' @export
prepare_table <- function(data_fixed_locs_points) {
  reef_data_synthetic <-
    data_fixed_locs_points |>
    dplyr::mutate(
      project_name = "synthetic",
      site_name = factor(paste(Reef, Site)),
      site_latitude = Latitude,
      site_longitude = Longitude,
      site_depth = Depth,
      survey_start_date = Date,
      survey_depth = Depth,
      survey_transect_number = Transect
      ) 
  ## Photo-transect specific
  if (data_type == "points") {
    reef_data_synthetic <-
      reef_data_synthetic |>
      dplyr::mutate(
        point_no = POINT_NO,
        point_machine_classification = Group
      )
  }
  if (data_type == "cover") {
    reef_data_synthetic <-
      reef_data_synthetic |> 
      dplyr::mutate(
        cover = Value,
        quad_no = as.numeric(factor(Quad)),
        point_machine_classification = Group
      )
  }
  reef_data_synthetic <-
    reef_data_synthetic |> 
        dplyr::select(
          project_name,
          site_name,
          site_latitude,
          site_longitude,
          site_depth,
          survey_start_date,
          survey_depth,
          survey_transect_number,
          any_of(c(
            "image_name",
            "point_id",
            "point_no",
            "point_machine_classification"
          )),
          any_of(c(
            "quad_no",
            "point_machine_classification",
            "cover"
          ))
        )
  ## Process data table to get percent cover at transect level 

  reef_data_synthetic <- synthos::select_process_reefs(reef_data_synthetic)
  return(reef_data_synthetic)
}


