#' Fine-Scale Percent Cover Estimates
#'
#' Generates fine-scale percent cover estimates by expanding benthic cover
#' values across quadrats. Applies depth effects, adds quadrat-level variation,
#' and returns an `sf` object with quadrat-based percent cover suitable for
#' downstream modelling and analysis.
#'
#' @title Fine-Scale Percent Cover
#'
#' @param data_fixed_locs_obs
#' An `sf` object representing fine-scale transect observations generated by
#' `sampling_design_fine_scale_fixed()`. Must contain:
#' \itemize{
#'   \item `Reef`, `Site`, `Transect`, `Year`, `Date`
#'   \item `HCC`, `SC`, `MA` – benthic cover values
#'   \item geometry associated with transects
#' }
#'
#' @param config_pt_lrge A list containing quadrat-level sampling parameters:
#' \itemize{
#'   \item `Depths` – number of depths per transect
#'   \item `Depth_effect_multiplier` – magnitude of depth effects
#'   \item `Number_of_quadrats_per_transect` – number of quadrats
#'   \item `Quad_sigma` – standard deviation of quadrat-level noise
#'   \item `seed` – optional random seed
#' }
#'
#' @return An `sf` object containing quadrat-level percent cover values with:
#' \itemize{
#'   \item Depth, Quadrats (`Quad`)
#'   \item Group (HCC, SC, MA)
#'   \item Percent cover values (`Value`) after depth + quadrat effects
#'   \item all original transect identifiers and geometry
#' }
#'
#' @details
#' This function:
#' \itemize{
#'   \item expands transects across depth levels
#'   \item reshapes benthic groups into long format
#'   \item adds a depth effect using a scaled random component
#'   \item generates quadrats and applies quadrat-level noise on the logit scale
#'   \item converts back to percent cover (0–100%)
#' }
#'
#' @author Murray
#' @export
sampling_design_fine_scale_cover <- function(data_fixed_locs_obs, config_pt) {
  set.seed(config_pt$seed)
  ## put on fold scale
  data_fixed_locs_obs <-
    data_fixed_locs_obs |>
    tidyr::crossing(Depth = seq(3, 10, length = config_pt$Depths)) |>
    tidyr::pivot_longer(cols = c(HCC, SC, MA),
      names_to = "Group",
      values_to = "Value") |>
    dplyr::group_by(Reef, Site, Transect, Year, Date) |>
    dplyr::mutate(Value = Value + rev(sort(config_pt$Depth_effect_multiplier *
                                      scale(rnorm(config_pt$Depths))))) |>
    dplyr::ungroup()
  ## Need to split the percentage cover into quadrats
  data_fixed_locs_obs <- data_fixed_locs_obs |>
    dplyr::group_by(Reef, Site, Transect, Year, Depth, Date) |>
    tidyr::crossing(
      Quad = paste0("Q", 1:config_pt$Number_of_quadrats_per_transect)
    ) |>
    dplyr::mutate(Value = 100* plogis(qlogis(Value / 100) + rnorm(dplyr::n(), 0, config_pt$Quad_sigma))) |> 
    dplyr::ungroup()
  return(data_fixed_locs_obs)
}
